window.WEEKLY_AFFILIATE_DEMO_REPORTS = [
  {
    id: "demo-alexey-2026-09-07",
    version: 8,
    weekStart: "2026-09-07",
    manager: "Алексей Орлов",
    metrics: { ftd: 94, activeAffiliates: 15, searchPlan: 28 },
    previousSearchPlan: "",
    acquisition: [
      {
        id: "demo-a-acq-1",
        collapsed: true,
        kind: "newAffiliate",
        partner: "content-br@example.com",
        geo: "BR",
        source: "SEO outreach",
        result: "Партнёр зарегистрирован, запросил условия по RevShare и список разрешённых источников.",
      },
      {
        id: "demo-a-acq-2",
        collapsed: true,
        kind: "newAffiliate",
        partner: "stream-cl@example.com",
        geo: "CL",
        source: "YouTube",
        result: "Провели первый звонок, партнёр готов дать тестовый объём после проверки трекинга.",
      },
      {
        id: "demo-a-acq-3",
        collapsed: true,
        kind: "newDeal",
        partner: "media-mx@example.com",
        geo: "MX",
        source: "Конференция",
        result: "Согласовали CPA и тестовый кап, запуск назначен на 15 сентября.",
      },
      {
        id: "demo-a-acq-4",
        collapsed: true,
        kind: "reactivated",
        partner: "legacy-br@example.com",
        geo: "BR",
        source: "CRM",
        result: "Партнёр вернулся после паузы и восстановил две интеграции.",
      },
    ],
    existing: [
      {
        id: "demo-a-existing-1",
        collapsed: true,
        email: "seo-br@example.com",
        geo: "BR",
        movement: "grew",
        reason: "Рост с 29 до 36 FTD после обновления лендинга и расширения семантики.",
        action: "Оставляем текущую связку и согласовываем дополнительный лимит.",
      },
      {
        id: "demo-a-existing-2",
        collapsed: true,
        email: "slots-mx@example.com",
        geo: "MX",
        movement: "fell",
        reason: "Падение с 18 до 11 FTD после выгорания основного креатива.",
        action: "Передали новые креативы, повторный запуск назначен на 16 сентября.",
      },
    ],
    problems: [
      {
        id: "demo-a-problem-1",
        collapsed: true,
        email: "stream-cl@example.com",
        problem: "В тестовых конверсиях партнёр не видел часть регистраций в своей статистике.",
        resolution: "Сверили клики и постбэки, нашли неверный subid. Исправление подтверждено тестом.",
      },
    ],
    nextWeek: [
      {
        id: "demo-a-next-1",
        collapsed: true,
        plan: "Запустить согласованный MX-тест с media-mx@example.com и получить первые данные по качеству.",
      },
      {
        id: "demo-a-next-2",
        collapsed: true,
        plan: "Подготовить персональные условия для content-br@example.com.",
      },
    ],
    priorities: [
      { id: "demo-a-priority-1", collapsed: true, text: "Запустить MX-тест без переноса даты." },
      { id: "demo-a-priority-2", collapsed: true, text: "Вернуть объём slots-mx@example.com." },
    ],
    topProblems: [
      { id: "demo-a-top-problem-1", collapsed: true, text: "Просадка объёма у slots-mx@example.com." },
      { id: "demo-a-top-problem-2", collapsed: true, text: "По CL потребовалась повторная настройка subid." },
    ],
    achievements: [
      { id: "demo-a-achievement-1", collapsed: true, text: "Реактивирован legacy-br@example.com." },
      { id: "demo-a-achievement-2", collapsed: true, text: "Согласован новый MX-тест с капом." },
    ],
    noSearch: false,
    noSearchReason: "",
    noExisting: false,
    noProblems: false,
    noTopProblems: false,
    noAchievements: false,
    createdAt: "2026-09-14T08:42:00+04:00",
    updatedAt: "2026-09-14T09:18:00+04:00",
    status: "submitted",
    submittedAt: "2026-09-14T09:18:00+04:00",
    comments: {
      "report:general": [
        {
          id: "demo-a-comment-1",
          author: "Руководитель",
          text: "После первых 20 FTD по MX отдельно сверим качество и решение по масштабированию.",
          createdAt: "2026-09-14T10:05:00+04:00",
          replyTo: "",
          context: "",
        },
      ],
    },
  },
  {
    id: "demo-marina-2026-09-07",
    version: 8,
    weekStart: "2026-09-07",
    manager: "Марина Соколова",
    metrics: { ftd: 79, activeAffiliates: 13, searchPlan: 22 },
    previousSearchPlan: "",
    acquisition: [
      {
        id: "demo-m-acq-1",
        collapsed: true,
        kind: "newAffiliate",
        partner: "telegram-pe@example.com",
        geo: "PE",
        source: "Telegram",
        result: "Партнёр прошёл квалификацию и запросил тестовые ссылки по двум продуктам.",
      },
      {
        id: "demo-m-acq-2",
        collapsed: true,
        kind: "newAffiliate",
        partner: "seo-br@example.com",
        geo: "BR",
        source: "SEO outreach",
        result: "Получили статистику, обсуждаем гибрид на первый месяц.",
      },
      {
        id: "demo-m-acq-3",
        collapsed: true,
        kind: "newDeal",
        partner: "social-cl@example.com",
        geo: "CL",
        source: "Instagram",
        result: "Согласовали CPA, кап 25 FTD и дату запуска 16 сентября.",
      },
      {
        id: "demo-m-acq-4",
        collapsed: true,
        kind: "reactivated",
        partner: "video-mx@example.com",
        geo: "MX",
        source: "CRM",
        result: "Партнёр возобновил размещения после согласования новых креативов.",
      },
    ],
    existing: [
      {
        id: "demo-m-existing-1",
        collapsed: true,
        email: "content-pe@example.com",
        geo: "PE",
        movement: "grew",
        reason: "Рост с 18 до 23 FTD после выхода нового обзора.",
        action: "Готовим второй материал и просим поднять оффер в сравнительной таблице.",
      },
      {
        id: "demo-m-existing-2",
        collapsed: true,
        email: "apps-br@example.com",
        geo: "BR",
        movement: "fell",
        reason: "Падение с 17 до 10 FTD после подключения новой рекламной площадки.",
        action: "Площадку отключили, следующий срез качества назначен на 17 сентября.",
      },
    ],
    problems: [
      {
        id: "demo-m-problem-1",
        collapsed: true,
        email: "apps-br@example.com",
        problem: "Доля невалидных кликов выросла после подключения новой площадки.",
        resolution: "Партнёр отключил площадку и передал source ID. Ждём новый срез качества.",
      },
    ],
    nextWeek: [
      {
        id: "demo-m-next-1",
        collapsed: true,
        plan: "Запустить social-cl@example.com в согласованный срок и проверить первые конверсии.",
      },
      {
        id: "demo-m-next-2",
        collapsed: true,
        plan: "Закрыть условия гибрида с seo-br@example.com и подготовить тестовые ссылки.",
      },
    ],
    priorities: [
      { id: "demo-m-priority-1", collapsed: true, text: "Запустить нового CL-партнёра с корректным трекингом." },
      { id: "demo-m-priority-2", collapsed: true, text: "Проверить качество apps-br@example.com после отключения площадки." },
    ],
    topProblems: [
      { id: "demo-m-top-problem-1", collapsed: true, text: "Повышенная доля невалидных кликов у apps-br@example.com." },
      { id: "demo-m-top-problem-2", collapsed: true, text: "Согласование гибрида по BR заняло больше времени, чем планировали." },
    ],
    achievements: [
      { id: "demo-m-achievement-1", collapsed: true, text: "Реактивирован video-mx@example.com." },
      { id: "demo-m-achievement-2", collapsed: true, text: "Согласован новый запуск social-cl@example.com." },
    ],
    noSearch: false,
    noSearchReason: "",
    noExisting: false,
    noProblems: false,
    noTopProblems: false,
    noAchievements: false,
    createdAt: "2026-09-14T09:06:00+04:00",
    updatedAt: "2026-09-14T09:41:00+04:00",
    status: "submitted",
    submittedAt: "2026-09-14T09:41:00+04:00",
    comments: {
      "report:general": [
        {
          id: "demo-m-comment-1",
          author: "Руководитель",
          text: "В следующем отчёте отдельно покажи изменение качества apps-br@example.com.",
          createdAt: "2026-09-14T10:16:00+04:00",
          replyTo: "",
          context: "",
        },
      ],
    },
  },
];
